In [1]:
import numpy as np
import pandas as pd
import math


data = pd.read_csv("dataMA6.csv")
print(data.shape)
print(data.columns.values)

"""
data["RENT"] = np.where(data["RENT"].between(0,500), 0, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(500,1000), 1, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(1000,1500), 2, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(1500,2000), 3, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(2000,2500), 4, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(2500,3000), 5, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(3000,3500), 6, data["RENT"])
data["RENT"] = np.where(data["RENT"]>3500, 7, data["RENT"])
y=data["RENT"]
"""
data["RENT"] = np.where(data["RENT"].between(0,1300), 0, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(1300,1900), 1, data["RENT"])
data["RENT"] = np.where(data["RENT"].between(1900,3000), 2, data["RENT"])
data["RENT"] = np.where(data["RENT"]>3000, 4, data["RENT"])
y=data["RENT"]

"""
data['INCTOT'] = np.where(data['INCTOT'].between(0,10000), 0, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(10000,20000), 1, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(20000,40000), 2, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(40000,60000), 3, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(60000,90000), 4, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(100000,150000), 5, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT'].between(150000,250000), 6, data['INCTOT'])
data['INCTOT'] = np.where(data['INCTOT']>250000, 7, data['INCTOT'])

"""

print(y.shape)
print(y.head(5))
#X = data[['CITY','SEX','AGE','SCHOOL','EDUC','EDUCD','GRADEATT','GRADEATTD','EMPSTAT','EMPSTATD','INCTOT','FTOTINC']]

#X = data[['CITY','SEX','AGE','SCHOOL','EDUC','GRADEATT','EMPSTAT','INCTOT','FAMSIZE']]
X = data[['CITY','SEX','AGE','SCHOOL','GRADEATT','FAMSIZE','EDUC','EMPSTAT','INCTOT','MORTGAGE','KITCHEN','FRIDGE','FTOTINC','MARST','RACE', 'PHONE','CINETHH']]
print(X.shape)
X['CITY'] = X['CITY'].replace(870, 1)
X['CITY'] = X['CITY'].replace(810, 0)
X['CITY'] = X['CITY'].replace(930, 2)
print(X.head(5))
X = pd.DataFrame(X,dtype=np.int)
X = X.dropna(axis=0)



(13844, 29)
['Unnamed: 0' 'YEAR' 'STATEFIP' 'CITY' 'CNTRY' 'MORTGAGE' 'RENT' 'RENTGRS'
 'VACANCY' 'KITCHEN' 'FRIDGE' 'PHONE' 'CINETHH' 'FAMSIZE' 'SEX' 'AGE'
 'MARST' 'RACE' 'RACED' 'CITIZEN' 'SCHOOL' 'EDUC' 'EDUCD' 'GRADEATT'
 'GRADEATTD' 'EMPSTAT' 'EMPSTATD' 'INCTOT' 'FTOTINC']
(13844,)
0    1
1    1
2    0
3    0
4    0
Name: RENT, dtype: int64
(13844, 17)
   CITY  SEX  AGE  SCHOOL  GRADEATT  FAMSIZE  EDUC  EMPSTAT  INCTOT  MORTGAGE  \
0     0    1   32       1         0        2    11        1   86000         0   
1     0    2   31       1         0        2    11        1   95000         0   
2     0    1   31       1         0        1     6        1   55000         0   
3     0    1   38       1         0        1     2        1   13200         0   
4  6670    2   31       1         0        6     5        3       0         0   

   KITCHEN  FRIDGE  FTOTINC  MARST  RACE  PHONE  CINETHH  
0        4       2   181000      1     4      2        1  
1        4       2   181000      1

F:\anaconda\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
F:\anaconda\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
F:\anaconda\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler()
#X1 = X[['CITY','SEX','SCHOOL','EDUC','GRADEATT','EMPSTAT']]
#X1 = X[["CITY","INCTOT","AGE"]]

from sklearn.model_selection import train_test_split
X_train1,X_test1, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train = X_train1[["INCTOT","AGE"]]
X_test = X_test1[["INCTOT","AGE"]]


scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)


from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=500, random_state=1, n_jobs=-1)
rf.fit(X_train, y_train)
print(rf.score(X_train, y_train))
ret = rf.predict(X_train)
print(ret[:5],y[:5])
score = sum((ret-y_train)**2)
print(score)

0.776226021350028
[0 0 0 0 2] 0    1
1    1
2    0
3    0
4    0
Name: RENT, dtype: int64
8692


In [3]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(15,7), random_state=1, max_iter=3000) 
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
pred = clf.predict(X_train)
print(pred[:10],y_train[:10])
score = sum((pred-y_train)**2)
print(score)

0.5744441769002328
[0 0 0 0 4 0 0 2 0 0] 3429     0
9897     0
9568     0
647      0
6752     2
6942     0
12939    0
7012     2
6503     1
6442     0
Name: RENT, dtype: int64
16753


In [4]:
from sklearn.linear_model import LogisticRegression

reg = LogisticRegression(max_iter=2000).fit(X_train, y_train)
print(reg.score(X_train, y_train))
pred2 = reg.predict(X_train)
print(pred2[:5])
pred5 = reg.predict(X_test)
score = (pred5==y_test).astype(int).mean()
print(score)

0.5707520667790352
[0 0 0 0 2]
0.5732851985559567


In [5]:
from sklearn.svm import SVC

clf = SVC(gamma='auto',C=1)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
pred3 = clf.predict(X_train)
print(pred3[:5])
print(y[:5])
score = (pred3==y_train).astype(int).mean()
pred4 = clf.predict(X_test)
score = (pred4==y_test).astype(int).mean()
print(score)

0.5738020707921984
[0 0 0 0 2]
0    1
1    1
2    0
3    0
4    0
Name: RENT, dtype: int64
0.5703971119133574


In [6]:
from sklearn.svm import LinearSVC

clf = LinearSVC(C=1, max_iter = 10000)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
pred8 = clf.predict(X_train)
print(pred3[:5])
print(y[:5])
score = (pred8==y_train).astype(int).mean()
pred9 = clf.predict(X_test)
score = (pred9==y_test).astype(int).mean()
print(score)

0.560317842523477
[0 0 0 0 2]
0    1
1    1
2    0
3    0
4    0
Name: RENT, dtype: int64
0.5588447653429602


In [7]:
from sklearn.neighbors import KNeighborsClassifier

def knn(X_train,X_test,y_train,y_test,k):
    """knn to train and return accuracy"""
    #scaler = StandardScaler()
    #X_train = scaler.fit_transform(X_train)
    #X_test = scaler.fit_transform(X_test)
    model = KNeighborsClassifier(n_neighbors=k, n_jobs=-1)
    model.fit(X_train,y_train)
    pred = model.predict(X_train)
    train_acc = (pred==y_train).astype(int).mean()
    pred = model.predict(X_test)
    test_acc = (pred==y_test).astype(int).mean()
    print("k="+ str(k))
    print("train accuracy="+ str(train_acc))
    print("test accuracy="+ str(test_acc))
    return train_acc,test_acc

#for i in range(100,150):
#    knn(X_train,X_test,y_train,y_test,i)
    
    
model = KNeighborsClassifier(n_neighbors=62, n_jobs=-1)
model.fit(X_train,y_train)
pred6 = model.predict(X_train)
train_acc = (pred6==y_train).astype(int).mean()
pred7 = model.predict(X_test)
test_acc = (pred7==y_test).astype(int).mean()
print(test_acc)

0.5566787003610109


In [8]:
#X2 = X[["CITY","INCTOT","AGE"]]
#X2 = X[["INCTOT"]]

X2 = X_train1[['CITY','SEX','SCHOOL','EDUC','GRADEATT','EMPSTAT','FAMSIZE','MORTGAGE','KITCHEN','FRIDGE','FTOTINC','MARST','RACE', 'PHONE','CINETHH']]
X2["PRED"] = pred2
X3 = X_test1[['CITY','SEX','SCHOOL','EDUC','GRADEATT','EMPSTAT','FAMSIZE','MORTGAGE','KITCHEN','FRIDGE','FTOTINC','MARST','RACE', 'PHONE','CINETHH']]
X3["PRED"] = pred5

X2= scaler.fit_transform(X2)

X3= scaler.transform(X3)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


reg = RandomForestClassifier(n_estimators=500, random_state=1, n_jobs=-1).fit(X2, y_train)
print(reg.score(X2, y_train))
pred = reg.predict(X3)

print(pred[:5])
print(y_test[:5])
score = (pred==y_test).astype(int).mean()
print(score)



F:\anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
F:\anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


0.9551328357010996
[1 0 0 0 0]
6214    0
4375    1
9901    0
8940    0
7959    0
Name: RENT, dtype: int64
0.5891696750902528


In [9]:
clf = SVC(gamma='auto',C=1.5)
clf.fit(X2, y_train)
predfinal = clf.predict(X2)
score = (predfinal==y_train).astype(int).mean()
print(score)
predfinal = clf.predict(X3)
score = (predfinal==y_test).astype(int).mean()
print(score)

0.6443534794124729
0.6259927797833935


In [10]:
clf = LogisticRegression(max_iter = 10000)
clf.fit(X2, y_train)
predfinal = clf.predict(X3)
score = (predfinal==y_test).astype(int).mean()
print(score)

0.6209386281588448


In [11]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100, random_state=1)
clf.fit(X2, y_train)
predfinal = clf.predict(X3)
score = (predfinal==y_test).astype(int).mean()
print(score)

0.6209386281588448


In [12]:
from sklearn.svm import LinearSVC
clf = LinearSVC(C=3, max_iter = 100000)
clf.fit(X2, y_train)
predfinal = clf.predict(X2)
score = (predfinal==y_train).astype(int).mean()
print(score)
predfinal = clf.predict(X3)
score = (predfinal==y_test).astype(int).mean()
print(score)

0.6209968697327233
0.6166064981949458
